### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by styleryt** [DragonCat4012/Bump-Bot#2]
If i try to type #bump i saw error
(node:12816) UnhandledPromiseRejectionWarning: ReferenceError: rawEmb is not defined
    at bump (Z:\partnership-help-reload\commands\bump.js:88:15)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12816) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12816) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
How to fix it??

**Comment by DragonCat4012** [comment]
oh yeah some files were´t the correct one, sry ^^" it is fixxed now ^^"

**Comment by styleryt** [comment]
Thx :)
