### ISSUE TITLE
-_- Again Error

### ISSUE THREAD

**Issue by styleryt** [DragonCat4012/Bump-Bot#3]
No past error, but now "rawEmb is not a function"

**Comment by styleryt** [comment]
You forgot to delete rawEmb on line 19

**Comment by styleryt** [comment]
emotes is not defined:
 I removed emotes from line 19 too, and added
const emotes = {
             false: "<: error1: 792082678424928276>",
             true: "<: success1: 792083031090790410>",
             partner: "<: partnerbadge: 792088866776809482>",
             inactivpartner: "",
             staff: "<: staffbadge: 792089050626523136>",
             inactivstaff: "",
             owner: "<: owner: 792089246042292245>",
             user: "<: user: 792090496544800778>",
             bot: "<: bot: 792089366661955615>"
         }

**Comment by styleryt** [comment]
The command is simply not accepted by the bot.

**Comment by DragonCat4012** [comment]
the emote thing is bc you couldnt find those emotes, thats why i changed them in my last commit
