### ISSUE TITLE
Bump bot didn't work

### ISSUE THREAD

**Issue by lordm121** [DragonCat4012/Bump-Bot#9]
Bump bot didn't work on console logs say that

at /app/index.js:197:22
    at Map.find (/rbd/pnpm-volume/db8797ba-ce22-47e7-8fcb-0a9befdbad59/node_modules/.registry.npmjs.org/@discordjs/collection/0.1.6/node_modules/@discordjs/collection/dist/index.js:161:17)
at Client.<anonymous> (/app/index.js:196:37)
(node:13946) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13946) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by DragonCat4012** [comment]
so your error appears when trying to bump or when you try to run any cmd?
